# Generated by Django 5.2.7 on 2025-10-30 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0001_initial'),
        ('lojas', '0014_remove_configuracaocliente_historico_compras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto em %', max_digits=5),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='desconto_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Desconto em valor', max_digits=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ para Pessoa Jurídica', max_length=18),
        ),
        migrations.AddField(
            model_name='lead',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF para Pessoa Física', max_length=14),
        ),
        migrations.AddField(
            model_name='lead',
            name='decisor',
            field=models.BooleanField(default=True, help_text='É o decisor da compra?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='inscricao_estadual',
            field=models.CharField(blank=True, help_text='Inscrição Estadual', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='inscricao_municipal',
            field=models.CharField(blank=True, help_text='Inscrição Municipal', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='interesse_principal',
            field=models.TextField(blank=True, help_text='Principal interesse/necessidade do cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='nome_fantasia',
            field=models.CharField(blank=True, help_text='Nome Fantasia para PJ', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='observacoes_interesse',
            field=models.TextField(blank=True, help_text='Detalhes específicos do interesse do cliente'),
        ),
        migrations.AddField(
            model_name='lead',
            name='orcamento_disponivel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orçamento disponível informado pelo cliente', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='prazo_decisao',
            field=models.CharField(blank=True, help_text='Prazo para tomada de decisão', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='ramo_atividade',
            field=models.CharField(blank=True, help_text='Ramo de atividade da empresa', max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='rg',
            field=models.CharField(blank=True, help_text='RG para Pessoa Física', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='tipo_pessoa',
            field=models.CharField(choices=[('fisica', 'Pessoa Física'), ('juridica', 'Pessoa Jurídica')], default='fisica', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo na empresa (para PF)', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='empresa',
            field=models.CharField(blank=True, help_text='Empresa onde trabalha (para PF)', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='nome',
            field=models.CharField(help_text='Nome completo para PF ou Razão Social para PJ', max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações gerais sobre o lead'),
        ),
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], default='servico', max_length=10)),
                ('codigo', models.CharField(blank=True, help_text='Código interno do produto/serviço', max_length=50)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('preco_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidade', models.CharField(default='un', help_text='Unidade de medida (un, h, kg, m², etc.)', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_servicos', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Produto/Serviço',
                'verbose_name_plural': 'Produtos/Serviços',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='produto_servico',
            field=models.ForeignKey(blank=True, help_text='Produto/Serviço cadastrado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_vendas.produtoservico'),
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('orcamento', 'Orçamento'), ('proposta', 'Proposta'), ('contrato', 'Contrato')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado para Assinatura'), ('visualizado', 'Visualizado'), ('assinado', 'Assinado'), ('rejeitado', 'Rejeitado'), ('expirado', 'Expirado')], default='pendente', max_length=20)),
                ('nome_signatario', models.CharField(max_length=200)),
                ('email_signatario', models.EmailField(max_length=254)),
                ('cpf_signatario', models.CharField(blank=True, max_length=14)),
                ('token_acesso', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('ip_assinatura', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('documento_original', models.FileField(blank=True, upload_to='assinaturas/originais/')),
                ('documento_assinado', models.FileField(blank=True, upload_to='assinaturas/assinados/')),
                ('hash_documento', models.CharField(blank=True, help_text='Hash SHA-256 do documento', max_length=64)),
                ('certificado_digital', models.TextField(blank=True, help_text='Dados do certificado usado na assinatura')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_vendas.contrato')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='crm_vendas.lead')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_vendas.orcamento')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_vendas.proposta')),
            ],
            options={
                'verbose_name': 'Assinatura Digital',
                'verbose_name_plural': 'Assinaturas Digitais',
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['lead', 'status'], name='crm_vendas__lead_id_0bf168_idx'), models.Index(fields=['token_acesso'], name='crm_vendas__token_a_eee6ff_idx'), models.Index(fields=['data_expiracao'], name='crm_vendas__data_ex_2c8b6a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='produtoservico',
            index=models.Index(fields=['loja', 'ativo'], name='crm_vendas__loja_id_21edf1_idx'),
        ),
        migrations.AddIndex(
            model_name='produtoservico',
            index=models.Index(fields=['tipo', 'categoria'], name='crm_vendas__tipo_990c9a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtoservico',
            unique_together={('loja', 'codigo')},
        ),
    ]
