# Generated by Django 5.2.7 on 2025-10-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_vendas', '0002_itemorcamento_desconto_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturadigital',
            name='tipo_signatario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('empresa', 'Empresa')], default='cliente', max_length=20),
        ),
    ]
