# Generated by Django 4.2.7 on 2025-10-05 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0003_loja_tipo_loja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('vencida', 'Vencida'), ('bloqueada', 'Bloqueada'), ('suspensa', 'Suspensa')], default='ativa', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('data_bloqueio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Bloqueio')),
                ('data_ultimo_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Último Pagamento')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('valor_pendente', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pendente')),
                ('dias_grace_period', models.IntegerField(default=5, verbose_name='Dias de Tolerância')),
                ('bloqueada', models.BooleanField(default=False, verbose_name='Bloqueada')),
                ('motivo_bloqueio', models.TextField(blank=True, verbose_name='Motivo do Bloqueio')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Controle Financeiro',
                'verbose_name_plural': 'Controles Financeiros',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='PlanoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Mensal')),
                ('dias_trial', models.IntegerField(default=30, verbose_name='Dias de Teste Grátis')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano Financeiro',
                'verbose_name_plural': 'Planos Financeiros',
                'ordering': ['valor_mensal'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('metodo_pagamento', models.CharField(max_length=50, verbose_name='Método de Pagamento')),
                ('dados_pagamento', models.JSONField(default=dict, verbose_name='Dados do Pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('controle_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_financeiro.controlefinanceiro', verbose_name='Controle Financeiro')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vencimento', 'Aviso de Vencimento'), ('bloqueio', 'Aviso de Bloqueio'), ('pagamento', 'Confirmação de Pagamento'), ('renovacao', 'Renovação Automática')], max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('enviada', models.BooleanField(default=False, verbose_name='Enviada')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('controle_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_financeiro.controlefinanceiro', verbose_name='Controle Financeiro')),
            ],
            options={
                'verbose_name': 'Notificação Financeira',
                'verbose_name_plural': 'Notificações Financeiras',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='controlefinanceiro',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_financeiro.planofinanceiro', verbose_name='Plano'),
        ),
    ]
