# Generated by Django 4.2.7 on 2025-10-05 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBoleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('codigo_banco', models.CharField(max_length=10, verbose_name='Código do Banco')),
                ('agencia', models.CharField(max_length=10, verbose_name='Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='Conta')),
                ('carteira', models.CharField(max_length=10, verbose_name='Carteira')),
                ('nome_beneficiario', models.CharField(max_length=200, verbose_name='Nome do Beneficiário')),
                ('cnpj_beneficiario', models.CharField(max_length=20, verbose_name='CNPJ do Beneficiário')),
                ('endereco_beneficiario', models.TextField(verbose_name='Endereço do Beneficiário')),
                ('instrucoes', models.TextField(blank=True, verbose_name='Instruções do Boleto')),
                ('multa', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Multa (%)')),
                ('juros', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Juros ao Mês (%)')),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Desconto (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Boleto',
                'verbose_name_plural': 'Configurações de Boletos',
            },
        ),
        migrations.CreateModel(
            name='BoletoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleto', models.CharField(max_length=50, verbose_name='Número do Boleto')),
                ('linha_digitavel', models.CharField(max_length=54, verbose_name='Linha Digitável')),
                ('codigo_barras', models.CharField(max_length=44, verbose_name='Código de Barras')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_financeiro.configuracaoboleto', verbose_name='Configuração')),
                ('controle_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_financeiro.controlefinanceiro', verbose_name='Controle Financeiro')),
            ],
            options={
                'verbose_name': 'Boleto Gerado',
                'verbose_name_plural': 'Boletos Gerados',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
