# Generated by otimização do sistema
from django.db import migrations

class Migration(migrations.Migration):
    
    dependencies = [
        ('controle_financeiro', '0001_initial'),
    ]
    
    operations = [
        # Comentar para manter dados históricos, mas não usar mais
        # migrations.DeleteModel(name='BoletoGerado'),
        # migrations.DeleteModel(name='ConfiguracaoBoleto'),
    ]
