# Generated by Django 4.2.7 on 2025-10-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0002_configuracaoboleto_boletogerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoboleto',
            name='codigo_cedente',
            field=models.CharField(blank=True, help_text='Código do cedente/beneficiário no banco', max_length=20, null=True, verbose_name='Código do Cedente'),
        ),
    ]
