# Generated by Django 4.2.7 on 2025-10-20 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0004_add_convenio_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaAsaas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asaas_id', models.CharField(max_length=100, unique=True, verbose_name='ID no Asaas')),
                ('customer_id', models.CharField(max_length=100, verbose_name='ID do Cliente no Asaas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('RECEIVED', 'Recebido'), ('CONFIRMED', 'Confirmado'), ('OVERDUE', 'Vencido'), ('REFUNDED', 'Estornado'), ('RECEIVED_IN_CASH', 'Recebido em Dinheiro'), ('REFUND_REQUESTED', 'Estorno Solicitado'), ('CHARGEBACK_REQUESTED', 'Chargeback Solicitado'), ('CHARGEBACK_DISPUTE', 'Disputa de Chargeback'), ('AWAITING_CHARGEBACK_REVERSAL', 'Aguardando Reversão'), ('DUNNING_REQUESTED', 'Cobrança Solicitada'), ('DUNNING_RECEIVED', 'Cobrança Recebida'), ('AWAITING_RISK_ANALYSIS', 'Aguardando Análise')], default='PENDING', max_length=30, verbose_name='Status')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('invoice_url', models.URLField(blank=True, verbose_name='URL do Boleto')),
                ('bank_slip_url', models.URLField(blank=True, verbose_name='URL do PDF')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Número da Fatura')),
                ('pix_qr_code', models.TextField(blank=True, verbose_name='QR Code PIX')),
                ('pix_copy_paste', models.TextField(blank=True, verbose_name='PIX Copia e Cola')),
                ('pix_expires_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração do PIX')),
                ('api_response', models.JSONField(default=dict, verbose_name='Resposta da API')),
                ('external_reference', models.CharField(blank=True, max_length=200, verbose_name='Referência Externa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('controle_financeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_financeiro.controlefinanceiro', verbose_name='Controle Financeiro')),
            ],
            options={
                'verbose_name': 'Cobrança Asaas',
                'verbose_name_plural': 'Cobranças Asaas',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
