# Generated by Django 4.2.7 on 2025-10-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0005_cobrancaasaas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoboleto',
            name='convenio',
            field=models.CharField(blank=True, help_text='Número do convênio com o banco', max_length=20, null=True, verbose_name='Número do Convênio'),
        ),
    ]
