# Generated by Django 5.2.7 on 2025-10-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_financeiro', '0002_otimizar_boletos'),
        ('controle_financeiro', '0006_alter_configuracaoboleto_convenio'),
    ]

    operations = [
    ]
