# Generated by Django 4.2.7 on 2025-10-28 18:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojas', '0014_remove_configuracaocliente_historico_compras_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_produtos_cqc', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
                'unique_together': {('loja', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='FornecedorComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Fornecedor')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('contato_responsavel', models.CharField(blank=True, max_length=255, verbose_name='Contato Responsável')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_cqc', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
                'unique_together': {('loja', 'cnpj')},
            },
        ),
        migrations.CreateModel(
            name='ProdutoComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Código de Barras')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Custo')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_qualidade_comercial.categoriaproduto', verbose_name='Categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_qualidade_comercial.fornecedorcomercial', verbose_name='Fornecedor')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_cqc', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
                'unique_together': {('loja', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='VendaComercial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_venda', models.CharField(max_length=50, verbose_name='Número da Venda')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Cliente')),
                ('cliente_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do Cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Cliente')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=50, verbose_name='Forma de Pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='concluida', max_length=50, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_cqc', to='lojas.loja')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-created_at'],
                'unique_together': {('loja', 'numero_venda')},
            },
        ),
        migrations.CreateModel(
            name='MetaQualidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Meta')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo_meta', models.CharField(choices=[('aprovacao_produtos', 'Aprovação de Produtos'), ('satisfacao_cliente', 'Satisfação do Cliente'), ('reducao_reclamacoes', 'Redução de Reclamações'), ('tempo_resolucao', 'Tempo de Resolução')], max_length=50, verbose_name='Tipo de Meta')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Meta')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Atual')),
                ('unidade_medida', models.CharField(blank=True, max_length=20, verbose_name='Unidade de Medida')),
                ('periodo_inicio', models.DateField(verbose_name='Período de Início')),
                ('periodo_fim', models.DateField(verbose_name='Período de Fim')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_qualidade_cqc', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Meta de Qualidade',
                'verbose_name_plural': 'Metas de Qualidade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_qualidade_comercial.produtocomercial', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='controle_qualidade_comercial.vendacomercial')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='ControleQualidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lote', models.CharField(blank=True, max_length=100, verbose_name='Lote')),
                ('data_fabricacao', models.DateField(blank=True, null=True, verbose_name='Data de Fabricação')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data de Validade')),
                ('data_inspecao', models.DateField(verbose_name='Data de Inspeção')),
                ('status_qualidade', models.CharField(choices=[('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('condicional', 'Condicional')], max_length=50, verbose_name='Status da Qualidade')),
                ('aparencia_visual', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Aparência Visual')),
                ('integridade_embalagem', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Integridade da Embalagem')),
                ('conformidade_especificacao', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Conformidade com Especificação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('acoes_corretivas', models.TextField(blank=True, verbose_name='Ações Corretivas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('inspetor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Inspetor')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles_qualidade_cqc', to='lojas.loja')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_qualidade_comercial.produtocomercial', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Controle de Qualidade',
                'verbose_name_plural': 'Controles de Qualidade',
                'ordering': ['-data_inspecao'],
            },
        ),
        migrations.CreateModel(
            name='ReclamacaoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_protocolo', models.CharField(max_length=50, verbose_name='Número do Protocolo')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do Cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone do Cliente')),
                ('tipo_reclamacao', models.CharField(choices=[('produto_defeituoso', 'Produto Defeituoso'), ('atendimento', 'Atendimento'), ('entrega', 'Entrega'), ('preco', 'Preço'), ('outros', 'Outros')], max_length=100, verbose_name='Tipo de Reclamação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('resolvida', 'Resolvida'), ('fechada', 'Fechada')], default='aberta', max_length=50, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridade')),
                ('resolucao', models.TextField(blank=True, verbose_name='Resolução')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('satisfacao_cliente', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Satisfação do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamacoes_cqc', to='lojas.loja')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_qualidade_comercial.produtocomercial', verbose_name='Produto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='controle_qualidade_comercial.vendacomercial', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Reclamação de Cliente',
                'verbose_name_plural': 'Reclamações de Clientes',
                'ordering': ['-created_at'],
                'unique_together': {('loja', 'numero_protocolo')},
            },
        ),
    ]
