# Generated by Django 5.2.7 on 2025-10-24 03:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500, verbose_name='Nome do Curso')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Curso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turma', models.CharField(max_length=200, verbose_name='Turma/Data')),
                ('link_token', models.CharField(max_length=100, unique=True, verbose_name='Token do Link')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Finalização')),
                ('total_avaliacoes', models.IntegerField(default=0, verbose_name='Total de Avaliações Recebidas')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Configuração de Avaliação',
                'verbose_name_plural': 'Configurações de Avaliação',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoResposta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nota_relacionamento_professor', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Relacionamento professor-aluno')),
                ('nota_didatica_professor', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Didática dos professores')),
                ('nota_dominio_assunto', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Domínio do assunto pelos professores')),
                ('professor_respeita_horarios', models.BooleanField(verbose_name='O professor respeita os horários e fica disponível para dúvidas após as aulas?')),
                ('origem_conhecimento', models.CharField(choices=[('indicacao', 'Indicação de ex-alunos/amigos'), ('site', 'Site da FATESA'), ('email_marketing', 'E-mail marketing'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google'), ('congressos', 'Congressos ou eventos'), ('telemarketing', 'Telemarketing'), ('material_impresso', 'Material impresso'), ('anuncios', 'Anúncios em revistas ou jornais'), ('outros', 'Outros')], max_length=50, verbose_name='Como você ficou sabendo da FATESA?')),
                ('motivo_escolha', models.CharField(choices=[('influencia_amigos', 'Influência de amigos'), ('tradicao', 'Tradição'), ('propaganda', 'Propaganda'), ('qualidade_ensino', 'Qualidade do ensino'), ('preco_competitivo', 'Preço competitivo'), ('estrutura', 'Estrutura'), ('outros', 'Outros')], max_length=50, verbose_name='O que motivou sua decisão de escolher a FATESA?')),
                ('nota_conteudo_teorico', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Satisfação com o conteúdo teórico')),
                ('nota_atividade_pratica', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Satisfação com a atividade prática')),
                ('nota_portaria', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Portaria')),
                ('nota_atendimento_aluno', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Atendimento ao aluno')),
                ('nota_secretaria', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Secretaria')),
                ('nota_recepcao_paciente', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Recepção Paciente')),
                ('nota_biblioteca', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Biblioteca')),
                ('nota_setor_comercial', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Setor Comercial')),
                ('nota_limpeza', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Limpeza')),
                ('nota_cantina', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Cantina')),
                ('comentarios_adicionais', models.TextField(blank=True, null=True, verbose_name='Comentários adicionais')),
                ('sugestoes_melhorias', models.TextField(blank=True, null=True, verbose_name='Sugestões de melhorias')),
                ('nome_aluno', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do aluno')),
                ('contato_aluno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato do aluno')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP do Aluno')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('data_resposta', models.DateTimeField(auto_now_add=True, verbose_name='Data da Resposta')),
                ('avaliacao_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='avaliacao_qualidade.avaliacaoconfig', verbose_name='Configuração da Avaliação')),
            ],
            options={
                'verbose_name': 'Resposta de Avaliação',
                'verbose_name_plural': 'Respostas de Avaliação',
                'ordering': ['-data_resposta'],
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Coordenador')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordenador_fatesa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Coordenador',
                'verbose_name_plural': 'Coordenadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='avaliacaoconfig',
            name='coordenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_qualidade.coordenador', verbose_name='Coordenador'),
        ),
        migrations.AddField(
            model_name='avaliacaoconfig',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_qualidade.curso', verbose_name='Curso'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Professor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('especialidade', models.CharField(blank=True, max_length=300, null=True, verbose_name='Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_fatesa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='avaliacaoconfig',
            name='professores',
            field=models.ManyToManyField(to='avaliacao_qualidade.professor', verbose_name='Professores'),
        ),
        migrations.CreateModel(
            name='RelatorioEstatisticas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('curso', 'Por Curso'), ('professor', 'Por Professor'), ('coordenador', 'Por Coordenador'), ('geral', 'Geral')], max_length=20)),
                ('referencia_id', models.CharField(max_length=100, verbose_name='ID de Referência')),
                ('referencia_nome', models.CharField(max_length=500, verbose_name='Nome de Referência')),
                ('total_avaliacoes', models.IntegerField(default=0)),
                ('media_professor', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('media_curso', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('media_administracao', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('media_geral', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('data_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Relatório de Estatísticas',
                'verbose_name_plural': 'Relatórios de Estatísticas',
                'ordering': ['-data_calculo'],
                'unique_together': {('tipo', 'referencia_id', 'data_inicio', 'data_fim')},
            },
        ),
    ]
