# Generated by Django 5.2.7 on 2025-10-24 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_qualidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_perfil', models.CharField(choices=[('diretoria', 'Diretoria'), ('coordenacao', 'Coordenação'), ('professor', 'Professor'), ('secretaria', 'Secretaria')], max_length=20, verbose_name='Tipo de Perfil')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('especialidade', models.CharField(blank=True, max_length=300, null=True, verbose_name='Especialidade')),
                ('cursos_coordenados', models.ManyToManyField(blank=True, related_name='coordenadores_perfil', to='avaliacao_qualidade.curso', verbose_name='Cursos Coordenados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_fatesa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuário',
                'ordering': ['nome_completo'],
            },
        ),
    ]
