# Generated by Django 5.2.7 on 2025-10-25 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_qualidade', '0003_alter_avaliacaoconfig_criado_por'),
        ('lojas', '0009_alter_loginpersonalizado_mostrar_link_recuperar_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='loja_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfis_fatesa', to='lojas.loja', verbose_name='Loja Associada'),
        ),
    ]
