# Generated by Django 5.2.7 on 2025-10-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_qualidade', '0004_perfilusuario_loja_associada'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='deve_alterar_senha',
            field=models.BooleanField(default=True, verbose_name='Deve alterar senha no próximo login'),
        ),
    ]
