# Generated by Django 5.2.7 on 2025-10-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_qualidade', '0005_perfilusuario_deve_alterar_senha'),
    ]

    operations = [
        # Garantir que a tabela de relacionamento many-to-many existe
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS avaliacao_qualidade_perfilusuario_cursos_coordenados (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                perfilusuario_id CHAR(32) NOT NULL REFERENCES avaliacao_qualidade_perfilusuario(id) DEFERRABLE INITIALLY DEFERRED,
                curso_id CHAR(32) NOT NULL REFERENCES avaliacao_qualidade_curso(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (perfilusuario_id, curso_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS avaliacao_qualidade_perfilusuario_cursos_coordenados;"
        ),
        
        # Criar índices para melhor performance
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS avaliacao_qualidade_perfilusuario_cursos_coordenados_perfilusuario_id 
            ON avaliacao_qualidade_perfilusuario_cursos_coordenados(perfilusuario_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS avaliacao_qualidade_perfilusuario_cursos_coordenados_perfilusuario_id;"
        ),
        
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS avaliacao_qualidade_perfilusuario_cursos_coordenados_curso_id 
            ON avaliacao_qualidade_perfilusuario_cursos_coordenados(curso_id);
            """,
            reverse_sql="DROP INDEX IF EXISTS avaliacao_qualidade_perfilusuario_cursos_coordenados_curso_id;"
        ),
    ]
