# Generated by Django 4.2.7 on 2025-10-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('error', 'Erro')], default='info', max_length=10, verbose_name='Tipo')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10, verbose_name='Prioridade')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='lojas.loja')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('total_vendas', models.IntegerField(default=0, verbose_name='Total de Vendas')),
                ('vendas_mes', models.IntegerField(default=0, verbose_name='Vendas do Mês')),
                ('vendas_semana', models.IntegerField(default=0, verbose_name='Vendas da Semana')),
                ('vendas_hoje', models.IntegerField(default=0, verbose_name='Vendas de Hoje')),
                ('receita_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita Total')),
                ('receita_mes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita do Mês')),
                ('receita_semana', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita da Semana')),
                ('receita_hoje', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita de Hoje')),
                ('total_clientes', models.IntegerField(default=0, verbose_name='Total de Clientes')),
                ('clientes_novos_mes', models.IntegerField(default=0, verbose_name='Clientes Novos do Mês')),
                ('total_produtos', models.IntegerField(default=0, verbose_name='Total de Produtos')),
                ('produtos_estoque_baixo', models.IntegerField(default=0, verbose_name='Produtos com Estoque Baixo')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Estatística do Dashboard',
                'verbose_name_plural': 'Estatísticas do Dashboard',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
