# Generated by Django 4.2.7 on 2025-10-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('is_loja_admin', models.BooleanField(default=False, verbose_name='Administrador de Loja')),
                ('is_super_admin', models.BooleanField(default=False, verbose_name='Super Administrador')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('ip_ultimo_acesso', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Último Acesso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=50, verbose_name='Ação')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('data_acesso', models.DateTimeField(auto_now_add=True, verbose_name='Data do Acesso')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Sucesso')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-data_acesso'],
            },
        ),
    ]
