# Generated by Django 4.2.7 on 2025-10-04 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Chave da Sessão')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('data_login', models.DateTimeField(auto_now_add=True, verbose_name='Data do Login')),
                ('ultima_atividade', models.DateTimeField(auto_now=True, verbose_name='Última Atividade')),
                ('ativa', models.BooleanField(default=True, verbose_name='Sessão Ativa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_ativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão Ativa',
                'verbose_name_plural': 'Sessões Ativas',
                'ordering': ['-data_login'],
            },
        ),
    ]
