# Generated by Django 4.2.7 on 2025-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_sessaoativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoativa',
            name='is_super_admin',
            field=models.BooleanField(default=False, verbose_name='Sessão de Super Admin'),
        ),
    ]
