# Generated by Django 4.2.7 on 2025-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_sessaoativa_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='deve_trocar_senha',
            field=models.BooleanField(default=True, verbose_name='Deve Trocar Senha'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='senha_alterada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Senha Alterada em'),
        ),
    ]
