# Generated by Django 4.2.7 on 2025-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfilusuario_deve_trocar_senha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='password_change_reminders_sent',
            field=models.IntegerField(default=0, verbose_name='Lembretes de Troca Enviados'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Senha Alterada em'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='provisional_password_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Senha Provisória Criada em'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='requires_password_change',
            field=models.BooleanField(default=False, verbose_name='Requer Troca de Senha'),
        ),
    ]
