# Generated by Django 5.2.7 on 2025-10-24 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_add_password_management_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacesso',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessaoativa',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_ativas', to=settings.AUTH_USER_MODEL),
        ),
    ]
