# Generated by Django 4.2.7 on 2025-10-03 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('db_name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Banco')),
                ('db_host', models.CharField(default='localhost', max_length=100, verbose_name='Host do Banco')),
                ('db_port', models.IntegerField(default=5432, verbose_name='Porta do Banco')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('suspensa', 'Suspensa')], default='ativa', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('senha_provisoria', models.CharField(blank=True, max_length=50, verbose_name='Senha Provisória')),
                ('senha_provisoria_expirada', models.BooleanField(default=False, verbose_name='Senha Expirada')),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja_admin', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.CharField(max_length=20, unique=True, verbose_name='Número da Venda')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='lojas.cliente')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('roupas', 'Roupas'), ('casa', 'Casa e Decoração'), ('esportes', 'Esportes'), ('livros', 'Livros'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='Código de Barras')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='lojas.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='lojas.venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='loja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='lojas.loja'),
        ),
        migrations.CreateModel(
            name='BackupLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=200, verbose_name='Nome do Arquivo')),
                ('tamanho_arquivo', models.BigIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('caminho_arquivo', models.CharField(max_length=500, verbose_name='Caminho do Arquivo')),
                ('data_backup', models.DateTimeField(auto_now_add=True, verbose_name='Data do Backup')),
                ('sucesso', models.BooleanField(default=True, verbose_name='Backup Realizado com Sucesso')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Backup da Loja',
                'verbose_name_plural': 'Backups das Lojas',
                'ordering': ['-data_backup'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('loja', 'cpf')},
        ),
    ]
