# Generated by Django 4.2.7 on 2025-10-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
