# Generated by Django 4.2.7 on 2025-10-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0001_initial'),
        ('lojas', '0002_alter_loja_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='tipo_loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulos.tipoloja', verbose_name='Tipo de Loja'),
        ),
    ]
