# Generated by Django 4.2.7 on 2025-10-11 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulos', '0001_initial'),
        ('lojas', '0004_mesa_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFuncionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('permissoes', models.JSONField(default=dict, help_text='Permissões específicas do tipo de funcionário', verbose_name='Permissões')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('tipo_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_funcionario', to='modulos.tipoloja', verbose_name='Tipo de Loja')),
            ],
            options={
                'verbose_name': 'Tipo de Funcionário',
                'verbose_name_plural': 'Tipos de Funcionário',
                'ordering': ['tipo_loja', 'nome'],
                'unique_together': {('nome', 'tipo_loja')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_funcionario', models.CharField(max_length=20, unique=True, verbose_name='Código do Funcionário')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='lojas.loja', verbose_name='Loja')),
                ('tipo_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='lojas.tipofuncionario', verbose_name='Tipo de Funcionário')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['loja', 'user__first_name', 'user__last_name'],
                'unique_together': {('loja', 'codigo_funcionario')},
            },
        ),
    ]
