# Generated by Django 4.2.7 on 2025-10-15 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0001_initial'),
        ('lojas', '0005_create_funcionario_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='plano_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planos.planocomercial', verbose_name='Plano Comercial'),
        ),
    ]
