# Generated by Django 5.2.7 on 2025-10-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_login_personalizado'),
        ('lojas', '0007_alter_loja_admin_user'),
    ]

    operations = [
    ]
