# Generated by Django 5.2.7 on 2025-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0008_merge_20251025_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpersonalizado',
            name='mostrar_link_recuperar_senha',
            field=models.BooleanField(default=True, verbose_name="Mostrar Link 'Esqueci Minha Senha'"),
        ),
        migrations.AlterField(
            model_name='loginpersonalizado',
            name='permitir_lembrar_senha',
            field=models.BooleanField(default=True, verbose_name="Permitir 'Lembrar de Mim'"),
        ),
    ]
