# Generated by Django 5.2.7 on 2025-10-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0009_alter_loginpersonalizado_mostrar_link_recuperar_senha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos_obrigatorios', models.JSONField(default=list, help_text="Lista de campos obrigatórios: ['nome', 'telefone', 'email']")),
                ('exige_cpf_cnpj', models.BooleanField(default=False)),
                ('valida_cpf_cnpj', models.BooleanField(default=True)),
                ('permite_cpf_duplicado', models.BooleanField(default=False)),
                ('exige_telefone', models.BooleanField(default=True)),
                ('exige_email', models.BooleanField(default=False)),
                ('exige_endereco', models.BooleanField(default=False)),
                ('permite_auto_cadastro', models.BooleanField(default=True)),
                ('aprova_automaticamente', models.BooleanField(default=True)),
                ('campos_personalizados', models.JSONField(default=dict, help_text='Campos extras específicos desta loja')),
                ('usa_segmentacao', models.BooleanField(default=False)),
                ('segmentos_disponiveis', models.JSONField(default=list, help_text="Segmentos de clientes: ['VIP', 'Regular', 'Novo']")),
                ('campos_listagem', models.JSONField(default=list, help_text='Campos a exibir na listagem de clientes')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_cliente', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Configuração de Cliente',
                'verbose_name_plural': 'Configurações de Clientes',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widgets_habilitados', models.JSONField(default=list, help_text='Lista de widgets a exibir no dashboard')),
                ('layout_colunas', models.IntegerField(choices=[(1, '1 Coluna'), (2, '2 Colunas'), (3, '3 Colunas'), (4, '4 Colunas')], default=3)),
                ('periodo_padrao', models.CharField(choices=[('hoje', 'Hoje'), ('semana_atual', 'Semana Atual'), ('mes_atual', 'Mês Atual'), ('trimestre_atual', 'Trimestre Atual'), ('ano_atual', 'Ano Atual'), ('personalizado', 'Personalizado')], default='mes_atual', max_length=20)),
                ('metricas_principais', models.JSONField(default=list, help_text="Métricas a destacar: ['vendas', 'clientes', 'produtos']")),
                ('graficos_habilitados', models.JSONField(default=list, help_text='Tipos de gráficos a exibir')),
                ('tema_cores', models.CharField(choices=[('padrao', 'Padrão'), ('azul', 'Azul'), ('verde', 'Verde'), ('roxo', 'Roxo'), ('laranja', 'Laranja'), ('personalizado', 'Personalizado')], default='padrao', max_length=20)),
                ('configuracoes_personalizadas', models.JSONField(default=dict, help_text='Configurações específicas desta loja')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_dashboard', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Configuração de Dashboard',
                'verbose_name_plural': 'Configurações de Dashboard',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos_obrigatorios', models.JSONField(default=list, help_text="Lista de campos obrigatórios: ['nome', 'preco', 'categoria']")),
                ('categorias_personalizadas', models.JSONField(default=list, help_text='Categorias específicas desta loja')),
                ('permite_preco_zero', models.BooleanField(default=False)),
                ('preco_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('controla_estoque', models.BooleanField(default=True)),
                ('estoque_minimo_padrao', models.IntegerField(default=0)),
                ('alerta_estoque_baixo', models.BooleanField(default=True)),
                ('gera_codigo_automatico', models.BooleanField(default=True)),
                ('prefixo_codigo', models.CharField(blank=True, max_length=10)),
                ('formato_codigo', models.CharField(default='AUTO', help_text='AUTO, MANUAL, ou padrão personalizado', max_length=50)),
                ('campos_personalizados', models.JSONField(default=dict, help_text='Campos extras específicos desta loja')),
                ('campos_listagem', models.JSONField(default=list, help_text='Campos a exibir na listagem de produtos')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_produto', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Configuração de Produto',
                'verbose_name_plural': 'Configurações de Produtos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao_automatica', models.BooleanField(default=True)),
                ('prefixo_numero', models.CharField(blank=True, max_length=10)),
                ('proximo_numero', models.IntegerField(default=1)),
                ('permite_desconto', models.BooleanField(default=True)),
                ('desconto_maximo_percentual', models.DecimalField(decimal_places=2, default=10.0, help_text='Desconto máximo em %', max_digits=5)),
                ('desconto_maximo_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Desconto máximo em valor', max_digits=10, null=True)),
                ('formas_pagamento_disponiveis', models.JSONField(default=list, help_text='Formas de pagamento aceitas')),
                ('baixa_estoque_automatica', models.BooleanField(default=True)),
                ('permite_venda_sem_estoque', models.BooleanField(default=False)),
                ('exige_cliente', models.BooleanField(default=False)),
                ('permite_cliente_generico', models.BooleanField(default=True)),
                ('imprime_automaticamente', models.BooleanField(default=False)),
                ('modelo_impressao', models.CharField(choices=[('padrao', 'Padrão'), ('termica', 'Térmica'), ('a4', 'A4'), ('personalizado', 'Personalizado')], default='padrao', max_length=50)),
                ('campos_personalizados', models.JSONField(default=dict, help_text='Campos extras específicos desta loja')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_venda', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Configuração de Venda',
                'verbose_name_plural': 'Configurações de Vendas',
            },
        ),
    ]
