# Generated by Django 5.2.7 on 2025-10-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0010_configuracaocliente_configuracaodashboard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracaovenda',
            options={},
        ),
        migrations.AddIndex(
            model_name='configuracaovenda',
            index=models.Index(fields=['loja'], name='lojas_confi_loja_id_27eda0_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracaovenda',
            index=models.Index(fields=['data_atualizacao'], name='lojas_confi_data_at_ac26c4_idx'),
        ),
    ]
