# Generated by Django 5.2.7 on 2025-10-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0011_alter_configuracaovenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaocliente',
            name='historico_compras',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaocliente',
            name='notificacoes_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracaocliente',
            name='permite_duplicatas',
            field=models.BooleanField(default=False),
        ),
    ]
