# Generated by Django 5.2.7 on 2025-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0012_configuracaocliente_historico_compras_and_more'),
    ]

    operations = [
        # Force add the missing columns with SQL
        migrations.RunSQL(
            "ALTER TABLE lojas_configuracaocliente ADD COLUMN permite_duplicatas BOOLEAN DEFAULT 0 NOT NULL;",
            reverse_sql="ALTER TABLE lojas_configuracaocliente DROP COLUMN permite_duplicatas;"
        ),
        migrations.RunSQL(
            "ALTER TABLE lojas_configuracaocliente ADD COLUMN historico_compras BOOLEAN DEFAULT 1 NOT NULL;",
            reverse_sql="ALTER TABLE lojas_configuracaocliente DROP COLUMN historico_compras;"
        ),
        migrations.RunSQL(
            "ALTER TABLE lojas_configuracaocliente ADD COLUMN notificacoes_email BOOLEAN DEFAULT 0 NOT NULL;",
            reverse_sql="ALTER TABLE lojas_configuracaocliente DROP COLUMN notificacoes_email;"
        ),
    ]
