# Generated by Django 5.2.7 on 2025-10-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0013_auto_20251027_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaocliente',
            name='historico_compras',
        ),
        migrations.RemoveField(
            model_name='configuracaocliente',
            name='notificacoes_email',
        ),
        migrations.RemoveField(
            model_name='configuracaocliente',
            name='permite_duplicatas',
        ),
    ]
