# Generated by Django 4.2.7 on 2025-10-03 17:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0002_alter_loja_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('suspensa', 'Suspensa'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='ativa', max_length=20, verbose_name='Status')),
                ('tipo_pagamento', models.CharField(choices=[('mensal', 'Mensal'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Tipo de Pagamento')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('data_cancelamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Cancelamento')),
                ('usuarios_online', models.PositiveIntegerField(default=0, verbose_name='Usuários Online Atualmente')),
                ('pdvs_ativos', models.PositiveIntegerField(default=0, verbose_name='PDVs Ativos Atualmente')),
                ('vendas_mes_atual', models.PositiveIntegerField(default=0, verbose_name='Vendas no Mês Atual')),
                ('limite_usuarios_atingido', models.BooleanField(default=False, verbose_name='Limite de Usuários Atingido')),
                ('limite_pdvs_atingido', models.BooleanField(default=False, verbose_name='Limite de PDVs Atingido')),
                ('limite_vendas_atingido', models.BooleanField(default=False, verbose_name='Limite de Vendas Atingido')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lojas.loja', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Assinatura da Loja',
                'verbose_name_plural': 'Assinaturas das Lojas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Plano')),
                ('tipo', models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='Tipo do Plano')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('max_usuarios_simultaneos', models.PositiveIntegerField(default=1, help_text='Número máximo de usuários que podem acessar simultaneamente', verbose_name='Máximo de Usuários Simultâneos')),
                ('max_pdvs', models.PositiveIntegerField(default=1, help_text='Número máximo de pontos de venda', verbose_name='Máximo de PDVs')),
                ('max_produtos', models.PositiveIntegerField(default=100, help_text='Número máximo de produtos que podem ser cadastrados', verbose_name='Máximo de Produtos')),
                ('max_clientes', models.PositiveIntegerField(default=100, help_text='Número máximo de clientes que podem ser cadastrados', verbose_name='Máximo de Clientes')),
                ('max_vendas_mes', models.PositiveIntegerField(default=100, help_text='Número máximo de vendas permitidas por mês', verbose_name='Máximo de Vendas por Mês')),
                ('backup_automatico', models.BooleanField(default=False, verbose_name='Backup Automático')),
                ('relatorios_avancados', models.BooleanField(default=False, verbose_name='Relatórios Avançados')),
                ('integracao_api', models.BooleanField(default=False, verbose_name='Integração API')),
                ('suporte_prioritario', models.BooleanField(default=False, verbose_name='Suporte Prioritário')),
                ('customizacao_avancada', models.BooleanField(default=False, verbose_name='Customização Avançada')),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Mensal (R$)')),
                ('preco_anual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Preço Anual (R$) - Desconto')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], default='ativo', max_length=20, verbose_name='Status')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('destaque', models.BooleanField(default=False, verbose_name='Plano em Destaque')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Plano Comercial',
                'verbose_name_plural': 'Planos Comerciais',
                'ordering': ['ordem_exibicao', 'preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('pdv_aberto', 'PDV Aberto'), ('pdv_fechado', 'PDV Fechado'), ('venda_realizada', 'Venda Realizada'), ('limite_atingido', 'Limite Atingido')], max_length=20, verbose_name='Tipo de Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('usuarios_online', models.PositiveIntegerField(default=0, verbose_name='Usuários Online')),
                ('pdvs_ativos', models.PositiveIntegerField(default=0, verbose_name='PDVs Ativos')),
                ('vendas_mes', models.PositiveIntegerField(default=0, verbose_name='Vendas no Mês')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('data_evento', models.DateTimeField(auto_now_add=True, verbose_name='Data do Evento')),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planos.assinaturaloja', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Histórico de Uso',
                'verbose_name_plural': 'Históricos de Uso',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.AddField(
            model_name='assinaturaloja',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planos.planocomercial', verbose_name='Plano'),
        ),
    ]
