# Generated by Django 5.2.7 on 2025-10-25 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0009_alter_loginpersonalizado_mostrar_link_recuperar_senha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LojaUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True, verbose_name='ID do usuário principal')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nome de usuário')),
                ('loja_access_profile', models.CharField(max_length=50, verbose_name='Perfil de acesso na loja')),
                ('permissions', models.JSONField(default=dict, verbose_name='Permissões específicas')),
                ('settings', models.JSONField(default=dict, verbose_name='Configurações do usuário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_access', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário da Loja',
                'verbose_name_plural': 'Perfis de Usuários da Loja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtendedUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_provisional_password', models.BooleanField(default=False, verbose_name='Tem senha provisória')),
                ('provisional_password_created', models.DateTimeField(blank=True, null=True, verbose_name='Data criação senha provisória')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data última alteração de senha')),
                ('user_type', models.CharField(choices=[('super_admin', 'Super Administrador'), ('loja_admin', 'Administrador de Loja'), ('loja_user', 'Usuário de Loja')], default='loja_user', max_length=20, verbose_name='Tipo de usuário')),
                ('database_alias', models.CharField(blank=True, max_length=50, verbose_name='Alias do banco')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('last_login_attempt', models.DateTimeField(blank=True, null=True, verbose_name='Última tentativa de login')),
                ('associated_loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_profiles', to='lojas.loja', verbose_name='Loja associada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extended_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil Estendido de Usuário',
                'verbose_name_plural': 'Perfis Estendidos de Usuário',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254, verbose_name='Email destinatário')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('email_type', models.CharField(choices=[('credentials', 'Credenciais'), ('recovery', 'Recuperação de senha'), ('notification', 'Notificação')], default='credentials', max_length=20, verbose_name='Tipo de email')),
                ('success', models.BooleanField(verbose_name='Enviado com sucesso')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de erro')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('attempts', models.IntegerField(default=1, verbose_name='Tentativas de envio')),
                ('fallback_used', models.BooleanField(default=False, verbose_name='Fallback utilizado')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='lojas.loja', verbose_name='Loja')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Email',
                'verbose_name_plural': 'Logs de Email',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'email_type'], name='email_crede_user_id_7b1842_idx'), models.Index(fields=['loja', 'sent_at'], name='email_crede_loja_id_59cff5_idx'), models.Index(fields=['success', 'sent_at'], name='email_crede_success_a5549b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordRecoveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_or_username', models.CharField(max_length=254, verbose_name='Email ou username usado')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Tentativa em')),
                ('success', models.BooleanField(verbose_name='Sucesso')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tentativa de Recuperação',
                'verbose_name_plural': 'Tentativas de Recuperação',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['user', 'attempted_at'], name='email_crede_user_id_265b8b_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='email_crede_ip_addr_3e2bb6_idx')],
            },
        ),
    ]
