# Generated by Django 4.2.7 on 2025-10-04 21:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLoja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(choices=[('conveniencia', 'Loja de Conveniência'), ('roupas', 'Loja de Roupas'), ('tintas', 'Loja de Tintas'), ('supermercado', 'Supermercado'), ('lanchonete', 'Lanchonete'), ('farmacia', 'Farmácia'), ('eletronicos', 'Eletrônicos'), ('casa_construcao', 'Casa e Construção'), ('livraria', 'Livraria'), ('outros', 'Outros')], max_length=50, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(default='fas fa-store', max_length=50, verbose_name='Ícone')),
                ('cor_primaria', models.CharField(default='#007bff', max_length=7, verbose_name='Cor Primária')),
                ('cor_secundaria', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor Secundária')),
                ('tem_categoria_produto', models.BooleanField(default=True, verbose_name='Tem Categoria de Produto')),
                ('tem_marca_produto', models.BooleanField(default=True, verbose_name='Tem Marca de Produto')),
                ('tem_tamanho_produto', models.BooleanField(default=False, verbose_name='Tem Tamanho de Produto')),
                ('tem_cor_produto', models.BooleanField(default=False, verbose_name='Tem Cor de Produto')),
                ('tem_peso_produto', models.BooleanField(default=False, verbose_name='Tem Peso de Produto')),
                ('tem_volume_produto', models.BooleanField(default=False, verbose_name='Tem Volume de Produto')),
                ('tem_data_validade', models.BooleanField(default=False, verbose_name='Tem Data de Validade')),
                ('tem_codigo_barras', models.BooleanField(default=True, verbose_name='Tem Código de Barras')),
                ('tem_estoque_minimo', models.BooleanField(default=True, verbose_name='Tem Estoque Mínimo')),
                ('tem_data_nascimento_cliente', models.BooleanField(default=True, verbose_name='Cliente: Data de Nascimento')),
                ('tem_sexo_cliente', models.BooleanField(default=True, verbose_name='Cliente: Sexo')),
                ('tem_cpf_cliente', models.BooleanField(default=True, verbose_name='Cliente: CPF')),
                ('tem_rg_cliente', models.BooleanField(default=False, verbose_name='Cliente: RG')),
                ('tem_cnpj_cliente', models.BooleanField(default=False, verbose_name='Cliente: CNPJ')),
                ('tem_desconto_venda', models.BooleanField(default=True, verbose_name='Venda: Desconto')),
                ('tem_taxa_entrega', models.BooleanField(default=False, verbose_name='Venda: Taxa de Entrega')),
                ('tem_mesa_venda', models.BooleanField(default=False, verbose_name='Venda: Mesa')),
                ('tem_garcom_venda', models.BooleanField(default=False, verbose_name='Venda: Garçom')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Tipo de Loja',
                'verbose_name_plural': 'Tipos de Loja',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ModuloLoja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Módulo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('icone', models.CharField(default='fas fa-cog', max_length=50, verbose_name='Ícone')),
                ('url', models.CharField(max_length=200, verbose_name='URL do Módulo')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='modulos.tipoloja')),
            ],
            options={
                'verbose_name': 'Módulo de Loja',
                'verbose_name_plural': 'Módulos de Loja',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Campo')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug do Campo')),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('decimal', 'Decimal'), ('data', 'Data'), ('hora', 'Hora'), ('boolean', 'Sim/Não'), ('escolha', 'Escolha Única'), ('multipla_escolha', 'Múltipla Escolha')], max_length=20, verbose_name='Tipo do Campo')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('opcoes', models.TextField(blank=True, null=True, verbose_name='Opções (uma por linha)')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='modulos.tipoloja')),
            ],
            options={
                'verbose_name': 'Campo Personalizado',
                'verbose_name_plural': 'Campos Personalizados',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('tipo_loja', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ValorCampoPersonalizado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.TextField(verbose_name='Valor')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='modulos.campopersonalizado')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='lojas.produto')),
            ],
            options={
                'verbose_name': 'Valor Campo Personalizado',
                'verbose_name_plural': 'Valores Campos Personalizados',
                'unique_together': {('campo', 'produto')},
            },
        ),
    ]
