# Generated by Django 4.2.7 on 2025-10-15 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_create_funcionario_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_agendamento', models.DateField(verbose_name='Data do Agendamento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Fim')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('confirmado', 'Confirmado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('faltou', 'Cliente Faltou')], default='agendado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('observacoes_pos_procedimento', models.TextField(blank=True, verbose_name='Observações Pós-Procedimento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='lojas.cliente', verbose_name='Cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_profissional', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data_agendamento', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloEmagrecimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Protocolo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo_protocolo', models.CharField(choices=[('drenagem', 'Drenagem Linfática'), ('criolipolise', 'Criolipólise'), ('radiofrequencia', 'Radiofrequência'), ('ultrassom', 'Ultrassom'), ('massagem_modeladora', 'Massagem Modeladora'), ('bandagem', 'Bandagem Redutora'), ('combinado', 'Protocolo Combinado')], max_length=20, verbose_name='Tipo de Protocolo')),
                ('numero_sessoes', models.IntegerField(verbose_name='Número de Sessões')),
                ('intervalo_dias', models.IntegerField(default=7, verbose_name='Intervalo entre Sessões (dias)')),
                ('duracao_sessao_minutos', models.IntegerField(verbose_name='Duração da Sessão (minutos)')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('preco_sessao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço por Sessão')),
                ('indicacoes', models.TextField(verbose_name='Indicações')),
                ('contraindicacoes', models.TextField(verbose_name='Contraindicações')),
                ('resultados_esperados', models.TextField(verbose_name='Resultados Esperados')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Protocolo de Emagrecimento',
                'verbose_name_plural': 'Protocolos de Emagrecimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ServicoEstetica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Serviço')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('facial', 'Tratamento Facial'), ('corporal', 'Tratamento Corporal'), ('injetavel', 'Procedimentos Injetáveis'), ('laser', 'Tratamentos a Laser'), ('depilacao', 'Depilação'), ('manicure', 'Manicure e Pedicure'), ('massagem', 'Massagens'), ('outros', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('duracao_minutos', models.IntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (45, '45 minutos'), (60, '1 hora'), (90, '1h30'), (120, '2 horas'), (180, '3 horas')], verbose_name='Duração')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional')),
                ('requer_consulta_medica', models.BooleanField(default=False, verbose_name='Requer Consulta Médica')),
                ('idade_minima', models.IntegerField(default=16, verbose_name='Idade Mínima')),
                ('contraindicacoes', models.TextField(blank=True, verbose_name='Contraindicações')),
                ('cuidados_pos_procedimento', models.TextField(blank=True, verbose_name='Cuidados Pós-Procedimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Serviço de Estética',
                'verbose_name_plural': 'Serviços de Estética',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='tipoloja',
            name='nome',
            field=models.CharField(choices=[('conveniencia', 'Loja de Conveniência'), ('roupas', 'Loja de Roupas'), ('tintas', 'Loja de Tintas'), ('supermercado', 'Supermercado'), ('lanchonete', 'Lanchonete'), ('farmacia', 'Farmácia'), ('eletronicos', 'Eletrônicos'), ('casa_construcao', 'Casa e Construção'), ('livraria', 'Livraria'), ('clinica_estetica', 'Clínica de Estética'), ('outros', 'Outros')], max_length=50, unique=True, verbose_name='Nome do Tipo'),
        ),
        migrations.CreateModel(
            name='Retorno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_retorno', models.CharField(choices=[('avaliacao', 'Avaliação'), ('manutencao', 'Manutenção'), ('complementar', 'Tratamento Complementar'), ('emergencia', 'Emergência')], max_length=20, verbose_name='Tipo de Retorno')),
                ('data_retorno', models.DateField(verbose_name='Data do Retorno')),
                ('hora_retorno', models.TimeField(verbose_name='Hora do Retorno')),
                ('motivo_retorno', models.TextField(verbose_name='Motivo do Retorno')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('agendamento_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retornos', to='modulos.agendamento', verbose_name='Agendamento Original')),
            ],
            options={
                'verbose_name': 'Retorno',
                'verbose_name_plural': 'Retornos',
                'ordering': ['data_retorno', 'hora_retorno'],
            },
        ),
        migrations.CreateModel(
            name='PacoteTratamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Pacote')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('numero_sessoes', models.IntegerField(verbose_name='Número de Sessões')),
                ('validade_dias', models.IntegerField(default=90, verbose_name='Validade (dias)')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Total')),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('protocolo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacotes', to='modulos.protocoloemagrecimento', verbose_name='Protocolo')),
                ('servicos', models.ManyToManyField(related_name='pacotes', to='modulos.servicoestetica', verbose_name='Serviços Incluídos')),
            ],
            options={
                'verbose_name': 'Pacote de Tratamento',
                'verbose_name_plural': 'Pacotes de Tratamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FichaAnamnese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pele', models.CharField(choices=[('normal', 'Normal'), ('oleosa', 'Oleosa'), ('seca', 'Seca'), ('mista', 'Mista'), ('sensivel', 'Sensível')], max_length=20, verbose_name='Tipo de Pele')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias Conhecidas')),
                ('medicamentos_uso', models.TextField(blank=True, verbose_name='Medicamentos em Uso')),
                ('tratamentos_anteriores', models.TextField(blank=True, verbose_name='Tratamentos Anteriores')),
                ('problemas_circulatorios', models.BooleanField(default=False, verbose_name='Problemas Circulatórios')),
                ('diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('hipertensao', models.BooleanField(default=False, verbose_name='Hipertensão')),
                ('gravidez', models.BooleanField(default=False, verbose_name='Gravidez')),
                ('amamentacao', models.BooleanField(default=False, verbose_name='Amamentação')),
                ('objetivos_tratamento', models.TextField(verbose_name='Objetivos do Tratamento')),
                ('expectativas', models.TextField(blank=True, verbose_name='Expectativas')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_anamnese', to='lojas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Ficha de Anamnese',
                'verbose_name_plural': 'Fichas de Anamnese',
            },
        ),
        migrations.CreateModel(
            name='EvolucaoTratamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peso_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Inicial (kg)')),
                ('peso_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso Atual (kg)')),
                ('medidas_corporais', models.TextField(blank=True, verbose_name='Medidas Corporais')),
                ('fotos_antes', models.TextField(blank=True, verbose_name='Fotos Antes (URLs)')),
                ('fotos_depois', models.TextField(blank=True, verbose_name='Fotos Depois (URLs)')),
                ('observacoes_profissional', models.TextField(verbose_name='Observações do Profissional')),
                ('observacoes_cliente', models.TextField(blank=True, verbose_name='Observações do Cliente')),
                ('proximos_passos', models.TextField(blank=True, verbose_name='Próximos Passos')),
                ('data_evolucao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Evolução')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='modulos.agendamento', verbose_name='Agendamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolucoes', to='lojas.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Evolução do Tratamento',
                'verbose_name_plural': 'Evoluções do Tratamento',
                'ordering': ['-data_evolucao'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='protocolo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='modulos.protocoloemagrecimento', verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='modulos.servicoestetica', verbose_name='Serviço'),
        ),
    ]
