# Generated by Django 5.2.7 on 2025-10-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_agendamento_protocoloemagrecimento_servicoestetica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoloja',
            name='tem_crm_cliente',
            field=models.BooleanField(default=False, verbose_name='Cliente: CRM'),
        ),
    ]
