# Generated by Django 5.2.7 on 2025-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_tipoloja_tem_crm_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoloja',
            name='nome',
            field=models.CharField(choices=[('conveniencia', 'Loja de Conveniência'), ('roupas', 'Loja de Roupas'), ('tintas', 'Loja de Tintas'), ('supermercado', 'Supermercado'), ('lanchonete', 'Lanchonete'), ('farmacia', 'Farmácia'), ('eletronicos', 'Eletrônicos'), ('casa_construcao', 'Casa e Construção'), ('livraria', 'Livraria'), ('clinica_estetica', 'Clínica de Estética'), ('controle_qualidade', 'Controle de Qualidade'), ('outros', 'Outros')], max_length=50, unique=True, verbose_name='Nome do Tipo'),
        ),
    ]
