# Generated by Django 5.2.7 on 2025-10-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_alter_tipoloja_nome'),
    ]

    operations = [
        # Remover campos de configuração específica que agora são individuais por loja
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_categoria_produto',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_marca_produto',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_tamanho_produto',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_cor_produto',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_peso_produto',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_volume_produto',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_data_validade',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_codigo_barras',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_estoque_minimo',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_data_nascimento_cliente',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_sexo_cliente',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_cpf_cliente',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_rg_cliente',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_cnpj_cliente',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_crm_cliente',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_desconto_venda',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_taxa_entrega',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_mesa_venda',
        ),
        migrations.RemoveField(
            model_name='tipoloja',
            name='tem_garcom_venda',
        ),
    ]
