# Generated by Django 4.2.7 on 2025-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_alter_tipoloja_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoloja',
            name='nome',
            field=models.CharField(choices=[('conveniencia', 'Loja de Conveniência'), ('roupas', 'Loja de Roupas'), ('tintas', 'Loja de Tintas'), ('supermercado', 'Supermercado'), ('lanchonete', 'Lanchonete'), ('farmacia', 'Farmácia'), ('eletronicos', 'Eletrônicos'), ('casa_construcao', 'Casa e Construção'), ('livraria', 'Livraria'), ('clinica_estetica', 'Clínica de Estética'), ('avaliacao_fatesa', 'Avaliação Educacional - FATESA'), ('dashboard_comercial', 'Dashboard Comercial e Qualidade'), ('crm_vendas', 'CRM de Vendas'), ('outros', 'Outros')], max_length=50, unique=True, verbose_name='Nome do Tipo'),
        ),
    ]
