# Generated by Django 5.2.7 on 2025-10-28 21:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0014_remove_configuracaocliente_historico_compras_and_more'),
        ('modulos', '0009_alter_tipoloja_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTipoLoja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('produto', 'Configurações de Produto'), ('cliente', 'Configurações de Cliente'), ('venda', 'Configurações de Venda'), ('dashboard', 'Configurações de Dashboard'), ('sistema', 'Configurações de Sistema')], max_length=20, verbose_name='Categoria')),
                ('chave', models.CharField(max_length=100, verbose_name='Chave da Configuração')),
                ('nome_exibicao', models.CharField(max_length=200, verbose_name='Nome para Exibição')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo_valor', models.CharField(choices=[('boolean', 'Sim/Não'), ('texto', 'Texto'), ('numero', 'Número'), ('decimal', 'Decimal'), ('lista', 'Lista de Opções'), ('json', 'JSON')], max_length=20, verbose_name='Tipo do Valor')),
                ('valor_padrao', models.TextField(blank=True, verbose_name='Valor Padrão')),
                ('opcoes_disponiveis', models.TextField(blank=True, verbose_name='Opções Disponíveis (uma por linha)')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('editavel_loja', models.BooleanField(default=True, verbose_name='Loja pode editar')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_padrao', to='modulos.tipoloja')),
            ],
            options={
                'verbose_name': 'Configuração Padrão do Tipo de Loja',
                'verbose_name_plural': 'Configurações Padrão dos Tipos de Loja',
                'ordering': ['categoria', 'ordem', 'nome_exibicao'],
                'unique_together': {('tipo_loja', 'chave')},
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoLoja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_personalizado', models.TextField(blank=True, verbose_name='Valor Personalizado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_especificas', to='lojas.loja')),
                ('configuracao_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.configuracaotipoloja', verbose_name='Configuração do Tipo')),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações das Lojas',
                'unique_together': {('loja', 'configuracao_tipo')},
            },
        ),
    ]
